### PR TITLE
Revamp zh_cn translation

### PR DESCRIPTION
**Pull request by Neubulae**
I'm first opening this as a draft for further constructions and improvements, the `zh_cn.json` underwent a reformat as an attempt to improve later diff'ing, hence a large diff.

### CODE REVIEW

**Comment by DaFuqs** [comment]
this is so huge. Tyvm!

**Comment by Neubulae** [comment]
I have to say I am very sorry for the delay. I haven't got time to work with the translation for the past month and I do not know how can I keep up with current patches. The translation wasn't even complete back at that time frame so I have less than zero idea how to port this to 1.19, I might need assistance over that issue.

**Comment by DaFuqs** [comment]
I'll help you out whereever I can. ✅
I can try to automate some stuff so I can hopefully get you some assistance with what values changed and which did not or figure out how to use CrowdIn.

Don't stress the newest update too much, since there will be a lot of changes still until they are finalized. Not that you put in effort to translate stuff that will be changed again.

**Comment by Neubulae** [comment]
Ah! Thanks for your kind help!

**Comment by DaFuqs** [comment]
As promised:
https://gist.github.com/DaFuqs/accd86f8c21359c647c01590ce180ee2

this is a current 1.19.2 lang file from the gap using all your translations to the current 1.19.2 file. All entries are in the order where they are on my current repo, so future comparisons are as easy as possible for you.

- entries that did not change kept your translation 1:1
- entries that changed from 1.18=>1.19.2 are marked as such and have both original and new content set in a comment
- new entries have a `new` comment and the english translation set
- entries of your translation that do not exist in current 1.19.2 are at the bottom. It's mostly renames of the banner pattern and wood entries plus some other renames of lang file keys, so no "real" removals for the most part. (like `item.spectrum.manual` => `item.spectrum.guidebook`)

If you like I can create you a diff for 1.18.2, too. Totally up to you.

Guidebook is very much subject to change still, so best to wait with that a bit. :)

**Comment by Mosklia** [comment]
Some problem has found right now:
- Both Lime Spore Blossom and Green Spore Blossom are translated to "绿色孢子花"（The first one should be “黄绿色孢子花”）；
- Light Gray Sapling is translated to "浅绿色树苗"；
- Downstone is translated to "黎明之石".

**Comment by DaFuqs** [comment]
I'll close this one for the time being, since there have been quite a few developments since then. But always feel free to @ me again and I'll generate a new diff 👌

**Comment by Neubulae** [comment]
Yeah we are having quite a few trouble trying to… do things neatly while dealing with irl issues.
We will dial in a new PR after the things are sorted.

**Pull request closed without merging**
