### PR TITLE
Estrogen Compat

### PR DESCRIPTION
**Pull request by MayaqqDev**
:3

### CODE REVIEW

**Review by DaFuqs — APPROVED** [review]
(❁´◡`❁)

**Comment by DaFuqs** [comment]
Wait, this does not add up. The tag is set as `spectrum/tags/entity_types/urine_giving`, but should it not be `estrogen/tags/entity_types/urine_giving`?

**Comment by MayaqqDev** [comment]
Oh wait yeah

**Comment by DaFuqs** [comment]
I will take care of that ✅

**Pull request merged**
