### PR TITLE
Renamed colored plank blocks

### PR DESCRIPTION
**Pull request by sudo-CuriousLad**
Refer to #33

### CODE REVIEW

**Comment by xanthian** [comment]
Looks like you did a find and replace but now you have a double space where plank was

**Comment by sudo-CuriousLad** [comment]
Huh, that got through

**Comment by sudo-CuriousLad** [comment]
@xanthian Now?

**Comment by DaFuqs** [comment]
Pretty sure we should not only rename the lang file entries only, but the whole block ids 😅

**Comment by sudo-CuriousLad** [comment]
OH NO YOU DID NOT

**Comment by DaFuqs** [comment]
This merges 1.19 data into the 1.18.2 branch. Closing  this one in favor of https://github.com/DaFuqs/Spectrum/pull/106

**Pull request closed without merging**
