### PR TITLE
Port Spectrum to 1.20

### PR DESCRIPTION
**Pull request by Noaaan**
# Spectrum 1.20
Will re-target towards a 1.20 branch once I can find the time.
Reason for a PR over directly pushing onto a separate branch is to note down what exactly changed between 1.19 and 1.20.
### Non-exhaustive list of version changes
- LootContextParameters.Builder get() no longer has a nullable. Check for the optional, or assume always safe?
- MatrixStack replaced most places with DrawContext
- Format of advancements changed. Most triggers now need a conditions + condition field, with a location predicate. The location predicate follows the old format most of the time, so main challenge is just to find and wrap them. 
- `world` is now private in tons of places, like entities, meaning you need to use `getWorld()` instead
- The `minecraft:alternative` loot condition is now named `minecraft:any_of`. A new `minecraft:all_of` also exists now
- A lot of packages moved. Registry for example now lives in its own packages instead of util. 
- Damage Sources underwent a major refactor. Since its now tag-driven some testing should be done to ensure it behaves correctly
- ExplosionModifiers was refactored, and needs testing to see whether it was ported correctly.
- ...and a ton more smaller changes. its over 1300 files changed, so its a bit hard to review.  
### Current problems
- ~~Advancements are broken. Mainly due to malformed `location` predicates.~~ Now fixed ✅
- ~~Patchouli does not work due to everything being placed under data.~~ fixed by Daf ✅
- ~~Colorful Hearts (formerly Health Overlay) does not use a DrawContext, meaning we have to make one ourselves for our compat~~ Now fixed ✅
- ~~`InkProjectileKillingCriterion` is not implemented correctly~~ Now fixed ✅
- ~~Chest Textures do not work, as they are not placed in any atlas at the moment. Only thing holding back updating this is verifying that the chests were properly renamed~~ Now fixed by moving into block atlas ✅ Needs verification as some chest names in lang and classes seem to be un-renamed. 
- ~~`SpectrumRegistries` should be ported to the new format which does not take in an Entity class, as it is deprecated.~~ Now fixed thanks to Electro ✅
- ~~`GatedSpectrumEmiRecipe` should be changed to respect the DynamicRegistryManager. It needs to grab this from some world, or pass an empty DRM (not ideal)~~Fixed by Electro ✅

### CODE REVIEW

**Comment by DaFuqs** [comment]
Created a 1.20.1 branch 👌

**Comment by Suya1671** [comment]
Any updates on this? The last commit was 2 weeks ago

**Comment by Noaaan** [comment]
This branch/PR is still being worked on. I will note that release-wise this will release at a later time than the DD update, so that there is time to test things. Its only a bit behind upstream at the moment

**Comment by Noaaan** [comment]
Noting that I just decided to try exploring the world, and experienced a crash related to a particle UV being weird. Will need to test further later.

Edit: Testing revealed this to be a crash with falling spore blossom particles, used for the dyed variants of the Spore Blossom block.

**Comment by DaFuqs** [comment]
I've taken my time to interact with most of the gameplay elements and fixed what I could today.
You can mark Patchouli as fixed. Seems to work perfecty now ✅ 
To add to your list:

BUGS:
- [x] Color Picker circle broken
- [x] Workstaff screen broken
- [x] Creative search does not find spectrum items (most likely a fractal issue; unregistered creative tabs?)
- [x] Preenchanted items don't are preenchanted in the creative gui (will change that in fractal by getting default stack)
- [x] Pastel transfers do not render the items
- [x] Particle Spawner gui broken
- [ ] Particle Spawner particles seem to have mostly the same trajectory, despite velocity variance?
- [x] Creative gui does not have a list of all available memories anymore (low prio)
- [ ] Ancient Statues have a weird offset in the inventory
- [x] On game launch there are 3x error "Spawn data: Value must be positive: 0; Value must be positive: 0" in the logs. Is this us?
- [ ] The 'arboretum' structure file lacks structure void blocks. (Probably missing in 1.19.2, too) 

CHANGES:
- [x] Rename "redstone_wireless" to "redstone_tranceiver"
- [x] Rename "vanilla_semi_permeable_glass" to "semi_permeable_glass"
- [x] Rename Noxwood Blocks to match vanilla
- [x] Fix unlock condition name for "milestones/reveal_azurite"
- [x] Update all structure files to 1.20 format (performance to skip the data fixer)

CHECKS:
- [ ] Playtest everything
- [x] Test if load conditions for worldgen work now (/raw/1.19.3/placed_features) => no :(

**Comment by Electro593** [comment]
I've put a few pull requests on @Noaaan's fork, notably fixing the color picker and creative search tab.

**Comment by DaFuqs** [comment]
Merging this, before github gives up.
3.5k files changed. Scary.

**Pull request merged**
