### PR TITLE
Another bunch of Programming Art textures are done!

### PR DESCRIPTION
**Pull request by Jenny77**
For some textures,I used my knowledge of minerals and plants to design them.I made light grey sapling and leaves look like scrap aluminum,made brown leaves look withered,green leaves look lively,and Vegetal looks like algae.
The design of Magenta Sapling is inspired by the game Semblance,and the design of Ominous Sapling,Midnight Abberation and Midnight Chip are inspired by the game Manifold Garden (that dark tree and those dark blocks),just because I'm an explorer in the world of games.
But sadly,I made this pull request too quick that I happened to leave Onyx Chiseled Calcite unfinished. Sorry for my mistake.

### CODE REVIEW

**Comment by DaFuqs** [comment]
There are quite a few pretty ones actually. love the item frames!

> Sorry for my mistake

No need to apologize at all! I am happy you are having fun. This is not a job, after all ;)

**Comment by Jenny77** [comment]
Well,I always tend to treat many things,including my hobbies and even playing,very seriously. Though that really makes me work better,I may be too cautious in some places. As an artist here,I am really happy and dedicated to provide quality textures to the players!

**Comment by DaFuqs** [comment]
Good news: Your textures are now ingame! 
Thanks to https://github.com/ExtraCrafTX/ProgrammerArtInjector
For reference, the programmer art textures are now stored in: /resources/programmer_art/assets/spectrum/textures/

**Comment by Jenny77** [comment]
Great! Thanks for your support,and I will work better and finish making those textures as soon and nice as I can!

**Pull request merged**
