### PR TITLE
Fix feature generation in the Deeper Down

### PR DESCRIPTION
**Pull request by f-raZ0R**
- [x] Make most features not override big chunks of cities (no more lakes, woo!)
- [x] unfuck lizard den generation to make it stop overlapping with rock clusters in the razor edge
- [x] kill mojang with hammers why are deltas so cursed
- [ ] unfuck tall mushroom generation in noxwood forests
- [ ] `AIR CHECK DISK IN NAME ONLY, FOR IT IS NEITHER`
- [x] Understand mojank enough to somehow obtain the ability to make two features not overlap each other (if this can't be done in time i am fine considering this to be out of scope)
eh this one's good enough besides the downstone in geodes im fine with this part
- [x] fix my block predicate to use a different function, so it cares about the y value, as right now all features using this predicate will not be placed if there is a structure ANYWHERE in their chunk (THIS IS THE MOST IMPORTANT PART, I DO NOT CONSIDER THIS PR MERGE-READY UNTIL I DO THIS)
- [ ] Add my block predicate to every feature that could conceivably overlap a structure, and stress test it to ensure it doesn't cause too much lag.

### CODE REVIEW

**Comment by f-raZ0R** [comment]
I feel kinda out of my depth a bit for the rest of the stuff on this checklist, and also i'm starting to feel exhausted and spoonless, so everyone else can feel free to help with this

**Comment by f-raZ0R** [comment]
never mind i think i can do most of it but idk how to fix basal marble/downstone blobs, and the mushrooms. got an idea for fixing my predicate, will do that tomorrow

**Comment by f-raZ0R** [comment]
anyone else is free to help with the mushrooms or air check disks

**Comment by f-raZ0R** [comment]
Screw it, mushrooms and air check discs are now out of scope, I'm undrafting this so the update is able to come out.

**Comment by f-raZ0R** [comment]
Wait i didn't make this depend on my library yet uh how do I unmark this as review

**Comment by Azzyypaaras** [comment]
,,,lol

**Comment by DaFuqs** [comment]
Did you do run a profiler?
I could imagine running that for ever, blockpos slowing things down immensely.

**Comment by f-raZ0R** [comment]
let this go to main 🚀

**Pull request merged**
