### PR TITLE
Chinese manual support.

### PR DESCRIPTION
**Pull request by PaperSummer**

### CODE REVIEW

**Comment by DaFuqs** [comment]
wow, thank you! I will check everything at the end of the week

**Comment by Neubulae** [comment]
Sorry for jumping in(and being late to the party) but I just browsed thru a bit and... it probably works out OK, but to be a bit nitpicky a few tweaks and correction would probably do better... Open to collab?

**Comment by PaperSummer** [comment]
> Sorry for jumping in(and being late to the party) but I just browsed thru a bit and... it probably works out OK, but to be a bit nitpicky a few tweaks and correction would probably do better... Open to collab?

I am not even good at English, sorry for that much translation mistakes. I already found some when i was playing… I am working on it. you can adjust that translation if you want.  thanks.

**Comment by Jenny77** [comment]
I'm good at English and have some idea in translating the manual,but I can't do such programming! Maybe I can provide some idea,and feel free to contact me!

**Comment by Neubulae** [comment]
I'm trying to do some work here on my branch!

**Pull request merged**
